version: "3.5"
services:
    api:
        build: 
            context: ./libera-api
        volumes:
            - "${API_PATH}/:/app"
        ports: 
            - 9001:8081
    db:
        build:
            context: ./libera-db
        restart: always
        environment:
            POSGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: libera
        ports:
            - 5433:5432

networks:
    libera-network:
        external: true

    
